# Generated by Django 3.2.9 on 2021-12-23 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Ivan', max_length=50)),
                ('surname', models.CharField(default='Ivanov', max_length=50)),
                ('father_name', models.CharField(default='Ivanovich', max_length=50)),
                ('is_teacher', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=400)),
                ('maxPoints', models.IntegerField(default=-1)),
                ('deadline', models.DateTimeField()),
                ('group', models.ManyToManyField(to='core.StudentGroup')),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.FileField(blank=True, upload_to='')),
                ('time', models.DateTimeField()),
                ('file', models.FileField(blank=True, upload_to='')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.profile')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.task')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='group',
            field=models.ManyToManyField(blank=True, to='core.StudentGroup'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
